services:
  - type: web
    name: darren-noortman-portfolio
    env: static
    buildCommand: npm install
    startCommand: npm start
    staticPublishPath: .
    envVars:
      - key: NODE_ENV
        value: production 